name: Reusuable Angular Build Workflow with Caching
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      node_version:
        required: true
        type: string


jobs:
  angular_build:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Caches
        uses: harshithkashyap/github-actions-workflows/.github/actions/restore-caches@main
        with:
          project_name: ${{ inputs.project_name }}
          node_version: ${{ inputs.node_version }}
          angular_caches: true
      
      - name: Angular Production Build
        run: |
          if [[ -d ./dist ]]; then
            echo "No build was run as there were no changes to the src/angular files."
          else
            npm run build:client:prod
          fi

      - name: Save Angular Build Cache
        uses: actions/cache@v4
        with:
          path: ./dist
          key: ${{ inputs.project_name }}-angular-build-${{ github.ref_name }}-${{ hashFiles('src/**/*') }}