name: 'Reusable Deploy to Staging Workflow'

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      node_version:
        required: true
        type: string
      package_filter:
        required: false
        type: string
        description: 'pnpm filter for workspace projects (e.g., "frontend" or "@repo/api-server")'
      angular_caches:
        required: false
        type: boolean
        default: false
      turborepo_caches:
        required: false
        type: boolean
        default: false
      turborepo_app_name:
        required: false
        type: string
        description: 'Name of the Turborepo app'
      azure_app_name:
        required: false
        type: string
        description: 'Azure App Service or Function App name (if different from project_name)'

permissions:
  id-token: write
  contents: read

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Restore Caches
        uses: FrameShiftLabs/github-actions-workflows/.github/actions/restore-caches@main
        with:
          project_name: ${{ inputs.project_name }}
          node_version: ${{ inputs.node_version }}
          angular_caches: ${{ inputs.angular_caches }}
          turborepo_caches: ${{ inputs.turborepo_caches }}

      - name: Prepare deployment
        id: prepare-deployment
        run: |
          if [ -n "${{ inputs.package_filter }}" ]; then
            # Check if this is an Azure Functions app (has host.json)
            if pnpm --filter=${{ inputs.package_filter }} exec test -f host.json; then
              echo "is_functions_app=true" >> $GITHUB_OUTPUT
              # Deploy Functions app with all dependencies resolved
              pnpm --filter=${{ inputs.package_filter }} deploy --prod deploy/
              
              (cd deploy/ && zip -rqy ../bundle.zip . --symlinks)
              
            else
              echo "is_functions_app=false" >> $GITHUB_OUTPUT
              STANDALONE_DIR="apps/${{ inputs.turborepo_app_name }}/.next/standalone"              
              (cd "$STANDALONE_DIR" && zip -rqy ../../../../bundle.zip . --symlinks)
            fi
            
          else
            # Single repo project: Build and package normally
            pnpm run build
            
            # Check for host.json in root to determine if this is a Functions app
            if [ -f "host.json" ]; then
              echo "is_functions_app=true" >> $GITHUB_OUTPUT
            else
              echo "is_functions_app=false" >> $GITHUB_OUTPUT
            fi
            
            # Remove dev dependencies and unused files
            pnpm prune --prod
            rm -rf \
              .git/ \
              .gitignore \
              .gitattributes \
              .editorconfig \
              package-lock.json \
              pnpm-lock.yaml
            
            # Create deployment archive
            zip -rqy bundle.zip . --symlinks
          fi
          
          echo "Bundle complete."
          ls -l -h bundle.zip

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Functions (Staging)
        id: deploy-functions-staging
        if: steps.prepare-deployment.outputs.is_functions_app == 'true'
        uses: azure/functions-action@v1
        with:
          app-name: ${{ inputs.azure_app_name || inputs.project_name }}
          slot-name: staging
          package: bundle.zip

      - name: Deploy to Azure App Service (Staging)
        id: deploy-webapp-staging
        if: steps.prepare-deployment.outputs.is_functions_app == 'false'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.azure_app_name || inputs.project_name }}
          slot-name: staging
          package: bundle.zip