name: 'Reusuable Deploy to Production Workflow'

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      node_version:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Restore Caches
        uses: Acrisure-Cyber-Services-dba-Otto-bot/otto-github-actions-workflows/.github/actions/restore-caches@main
        with:
          project_name: ${{ inputs.project_name }}
          node_version: ${{ inputs.node_version }}
      
      - name: Build TypeScript files
        run: npm run build:prod
      
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Swap Azure App Service staging and production slots
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az webapp deployment slot swap \
              --name ${{ inputs.project_name }} \
              --resource-group ${{ vars.RESOURCE_GROUP }} \
              --slot staging \
              --target-slot production