name: 'Reusable Deploy to Production Workflow'

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      node_version:
        required: true
        type: string
      angular_caches:
        required: false
        type: boolean
        default: false
      turborepo_caches:
        required: false
        type: boolean
        default: false
      azure_app_name:
        required: false
        type: string
        description: 'Azure App Service or Function App name (if different from project_name)'

permissions:
  id-token: write
  contents: read

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Restore Caches
        uses: harshithkashyap/github-actions-workflows/.github/actions/restore-caches@main
        with:
          project_name: ${{ inputs.project_name }}
          node_version: ${{ inputs.node_version }}
          angular_caches: ${{ inputs.angular_caches }}
          turborepo_caches: ${{ inputs.turborepo_caches }}
      
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Swap Azure App Service / Functions App staging and production slots
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az webapp deployment slot swap \
              --name ${{ inputs.azure_app_name || inputs.project_name }} \
              --resource-group ${{ vars.RESOURCE_GROUP }} \
              --slot staging \
              --target-slot production