name: 'Restore Repository and dependencies Cache'
description: 'Restores the repository and pnpm dependencies cache for a given project and commit SHA.'
inputs:
  project_name:
    description: 'The name of the project'
    required: true
  node_version:
    description: 'The Node.js version to use'
    required: true
  angular_caches:
    description: 'Whether to restore Angular build caches'
    required: false
    default: 'false'
  turborepo_caches:
    description: 'Whether to restore turborepo build caches'
    required: false
    default: 'false'
  pnpm_package_json_file:
    description: 'The path to the package.json file for pnpm setup (usually root package.json)'
    required: true
    default: 'package.json'

runs:
  using: 'composite'
  steps:
    - name: Restore repository cache
      uses: actions/cache@v4
      with:
        path: .
        key: ${{ inputs.project_name }}-repo-${{ github.sha }}
      
    - name: Restore pnpm cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.pnpm-store
          node_modules
          apps/*/node_modules
          packages/*/node_modules
        key: ${{ inputs.project_name }}-pnpm-dependencies-${{ github.ref_name }}-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: ${{ inputs.pnpm_package_json_file }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'pnpm'

    - name: Restore Angular Build and Cache Files
      if: ${{ inputs.angular_caches == 'true' }}
      uses: actions/cache@v4
      with:
        path: ./dist
        key: ${{ inputs.project_name }}-angular-build-${{ hashFiles('src/**/*') }}

    - name: Restore Turborepo Build Cache
      if: ${{ inputs.turborepo_caches == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          .turbo
          apps/*/.next
          apps/*/.turbo
          apps/*/dist
          apps/*/build
          packages/*/.turbo
          packages/*/dist
          packages/*/build
          packages/*/src/**/*.js
          packages/*/src/**/*.js.map
          packages/*/src/**/*.d.ts
          packages/*/src/**/*.d.ts.map
          node_modules/.cache
        key: ${{ inputs.project_name }}-turborepo-build-${{ github.ref_name }}-${{ hashFiles('**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx', '**/package.json', 'turbo.json', 'pnpm-lock.yaml') }}
        restore-keys: |
          ${{ inputs.project_name }}-turborepo-build-${{ github.ref_name }}-
          ${{ inputs.project_name }}-turborepo-build-
