name: 'Restore Repository and dependencies Cache'
description: 'Restores the repository and pnpm dependencies cache, and optionally sets up Turborepo remote caching for a given project and commit SHA.'
inputs:
  project_name:
    description: 'The name of the project'
    required: true
  node_version:
    description: 'The Node.js version to use'
    required: true
  angular_caches:
    description: 'Whether to restore Angular build caches'
    required: false
    default: 'false'
  turborepo_caches:
    description: 'Whether to set up Turborepo remote caching for turbo build/lint/test commands'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Restore repository cache
      uses: actions/cache@v4
      with:
        path: .
        key: ${{ inputs.project_name }}-repo-${{ github.sha }}
      
    - name: Restore pnpm cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          apps/*/node_modules
          packages/*/node_modules
        key: ${{ inputs.project_name }}-pnpm-dependencies-${{ github.ref_name }}-${{ hashFiles('pnpm-lock.yaml') }}
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}

    - name: Restore Angular Build and Cache Files
      if: ${{ inputs.angular_caches == 'true' }}
      uses: actions/cache@v4
      with:
        path: ./dist
        key: ${{ inputs.project_name }}-angular-build-${{ hashFiles('src/**/*') }}

    - name: Setup Turborepo Remote Caching
      if: ${{ inputs.turborepo_caches == 'true' }}
      uses: rharkor/caching-for-turbo@v2.3.1
      with:
        cache-prefix: ${{ inputs.project_name }}-turborepo-
        max-age: 2w
        max-size: 5gb

